#!/usr/bin/env python3
"""Regenerate dependencies.lock: the pinned wheels fetch_dependencies.sh unpacks.

Run this only when bumping a version below. Wheels are used purely as zip
archives of native libraries; no Python from them is ever imported.
"""

import json
import re
import urllib.request
from pathlib import Path

TORCH_VERSION = "2.10.0"
TORCH_CUDA = "cu130"
PYARROW_VERSION = "25.0.1"
# Any CPython tag works: only the native libraries inside the wheels are used.
WHEEL_PYTHON = "cp312"

# lock platform -> wheel platform tag suffix
PLATFORMS = {
    "linux-x86_64": "manylinux_2_28_x86_64",
    "linux-aarch64": "manylinux_2_28_aarch64",
    "macos-arm64": "macosx_11_0_arm64",
}
TORCH_INDEX = "https://download.pytorch.org/whl"
LOCK = Path(__file__).resolve().parents[1] / "dependencies.lock"


def fetch(url):
    request = urllib.request.Request(url, headers={"User-Agent": "curl/8"})
    with urllib.request.urlopen(request) as response:
        return response.read().decode()


def torch_wheel(variant, platform_tag):
    """Return (url, sha256) of the torch wheel from PyTorch's index."""
    local = "cpu" if variant == "cpu" else TORCH_CUDA
    page = fetch(f"{TORCH_INDEX}/{local}/torch/")
    local_tag = "" if platform_tag.startswith("macosx") else f"%2B{local}"
    abi = "none" if platform_tag.startswith("macosx") else WHEEL_PYTHON
    # macOS wheels may carry a build tag (-1, -2, ...); pip prefers the highest.
    pattern = re.compile(
        rf'href="[^"]*?/(torch-{re.escape(TORCH_VERSION)}{local_tag}(?:-(\d+))?'
        rf'-{WHEEL_PYTHON}-{abi}-{re.escape(platform_tag)}\.whl)#sha256=([0-9a-f]{{64}})"'
    )
    matches = [(int(build or 0), name, sha) for name, build, sha in pattern.findall(page)]
    if not matches:
        raise SystemExit(f"no torch {TORCH_VERSION} {local} wheel for {platform_tag}")
    _, name, sha = max(matches)
    return f"{TORCH_INDEX}/{local}/{name}", sha


def pypi_wheel(package, version, accept):
    """Return (url, sha256) of the first PyPI wheel whose filename passes accept."""
    files = json.loads(fetch(f"https://pypi.org/pypi/{package}/{version}/json"))["urls"]
    for f in files:
        if f["filename"].endswith(".whl") and accept(f["filename"]):
            return f["url"], f["digests"]["sha256"]
    raise SystemExit(f"no matching wheel for {package}=={version}")


def nvidia_pins(torch_url):
    """Exact nvidia-* pins from the torch wheel's metadata."""
    metadata = fetch(torch_url + ".metadata")
    pins = re.findall(r"^Requires-Dist: (nvidia-[a-z0-9-]+)==([^;\s]+)", metadata, re.M)
    if not pins:
        raise SystemExit(f"no nvidia-* pins in {torch_url}.metadata")
    return pins


def main():
    lines = [
        "# Generated by scripts/lock_dependencies.py -- do not edit by hand.",
        f"# torch {TORCH_VERSION} (cpu, {TORCH_CUDA}), pyarrow {PYARROW_VERSION}",
        "# <platform> <variant> <target> <sha256> <url>",
    ]
    for platform, tag in PLATFORMS.items():
        arch = tag.rsplit("_", 1)[-1] if tag.startswith("manylinux") else None
        variants = ["cpu", "cuda"] if arch else ["cpu"]
        for variant in variants:
            url, sha = torch_wheel(variant, tag)
            lines.append(f"{platform} {variant} libtorch {sha} {url}")
            if variant == "cuda":
                for package, version in nvidia_pins(url):
                    nv_url, nv_sha = pypi_wheel(
                        package, version,
                        lambda name: "manylinux" in name and name.endswith(f"_{arch}.whl"))
                    lines.append(f"{platform} cuda nvidia {nv_sha} {nv_url}")
        pa_tag = "macosx_12_0_arm64" if not arch else tag
        url, sha = pypi_wheel("pyarrow", PYARROW_VERSION,
                              lambda name: name.endswith(f"-{WHEEL_PYTHON}-{WHEEL_PYTHON}-{pa_tag}.whl"))
        lines.append(f"{platform} any arrow {sha} {url}")
    LOCK.write_text("\n".join(lines) + "\n")
    print(f"wrote {LOCK} ({len(lines) - 3} wheels)")


if __name__ == "__main__":
    main()
